### ISSUE TITLE
Migrate to GitHub Actions.

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/renature#109]
At Formidable, we're beginning to migrate all of our repositories off of Travis to use GitHub Actions. For `renature`, this migration should handle the following:

- Runs all current CI steps on both Node v12 and v14
- Bring over all necessary secrets for automated deployments of the docs site. This includes:
  - GitHub tokens
  - Surge tokens
  - AWS tokens

**Comment by ryan-roemer** [comment]
Ping me when you get around to this. The GH token may already be magically in place (you’ll need the other ones as secrets)

**Comment by parkerziegler** [comment]
I was actually going to reach out about this sometime this week @ryan-roemer! Already a few steps ahead of me 😅 Thanks for looking out!
