### ISSUE TITLE
Documentation - Broken link

### ISSUE THREAD

**Issue by joseph-passineau** [FormidableLabs/renature#55]
Hi,

The "View All" button link is wrong.
https://github.com/FormidableLabs/renature/blob/master/docs/src/screens/home/more-oss.js#L104
line: 104

This cause the link to be: 
https://formidable.com/open-source/renature/https://formidable.com/open-source/

What it should be:
https://formidable.com/open-source/

Should probably be:
`<Button light to="open-source/">`

**Comment by parkerziegler** [comment]
❤️ Thanks @joseph-passineau! Would you be interested in contributing this fix since you've basically already fixed it 😂 If not I'll take care of it 🤗

**Comment by joseph-passineau** [comment]
Sure, I'll do that. 👌
