### ISSUE TITLE
ReasonReact support?

### ISSUE THREAD

**Issue by BlueHotDog** [FormidableLabs/renature#56]
would be awesome to be able to use it in ReasonReact.. looks like it's almost ready. or did i miss something and i can do it?

**Comment by parkerziegler** [comment]
👋 Hey @BlueHotDog! We don't currently have ReasonReact support in this repo. While a lot of the core underlying math and physics that powers these animations is written in Reason, the public API is still 100% TS. You certainly could write bindings for it if you like, but we currently don't support them here and it's not on my roadmap for the scope of this project.

**Comment by parkerziegler** [comment]
Closing this as we have no plans to support ReasonReact from this repo. If other folks want to take up this work in a separate repo, they are free to do so!
