### ISSUE TITLE
Gallery overflows horizontally in Chrome

### ISSUE THREAD

**Issue by keithort** [FormidableLabs/renature#79]
This is what I am seeing in Chrome 84 on Windows 10 for all of the samples in the Gallery. Firefox, Edge, and IE11 render fine.

![image](https://user-images.githubusercontent.com/1872665/88323883-e6864d00-ccf0-11ea-94f9-0b422ecea3c4.png)

**Comment by parkerziegler** [comment]
Thanks @keithort, should be fixed once the above PR is merged 🚀
